### ISSUE TITLE
Bipartite graphs

### ISSUE THREAD

**Issue by erenarkangil** [ferencberes/online-node2vec#2]
Hey there,

Thank you for your contribution. Did you test this algorithm on bipartite graphs as well? What would you expect for possible results?

Cheers.

**Comment by ferencberes** [comment]
Hi,

No, I didn't test these algorithms for bipartite graphs. In general, I think that for such graphs simple online matrix factorization  would work quite well that is commonly used for problems related to online recommender systems.

Best,
Ferenc
